"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import type { Verification, VerificationResult } from "@/lib/types";
import { StageSequence } from "@/components/StageSequence";
import { ResultPanel } from "@/components/ResultPanel";
import { AgentSimulator } from "@/components/AgentSimulator";

export default function VerifyPage() {
  const { id } = useParams<{ id: string }>(); const [verification, setVerification] = useState<Verification | null>(null); const [result, setResult] = useState<VerificationResult | null>(null); const [running, setRunning] = useState(false); const [revealed, setRevealed] = useState(false); const [error, setError] = useState<string | null>(null); const [notFound, setNotFound] = useState(false); const bootedRef = useRef(false);
  useEffect(() => { if (bootedRef.current) return; bootedRef.current = true; (async () => { try { const res = await fetch(`/api/verifications/${id}`); if (!res.ok) throw new Error("not found"); const { verification: v } = await res.json(); setVerification(v); let realResult = v.result ?? null; if (!realResult) { const vr = await fetch(`/api/verifications/${id}/verify`, { method: "POST" }); const data = await vr.json(); if (!vr.ok) throw new Error(data.error ?? "Verification failed"); realResult = data.result; } setResult(realResult); setRunning(true); } catch (err) { const msg = err instanceof Error ? err.message : "Failed to load verification"; if (msg === "not found") setNotFound(true); else setError(msg); } })(); }, [id]);
  if (notFound) return <div className="mx-auto max-w-2xl px-5 py-24 text-center"><h1 className="text-2xl font-bold">Verification not found</h1><Link href="/jobs" className="btn-secondary mt-6 inline-flex">← Back to dashboard</Link></div>;
  if (!verification) return <div className="mx-auto max-w-2xl px-5 py-24 text-center text-[var(--muted)]"><span className="pulse-glow">Loading agreement…</span></div>;
  return <div className="mx-auto max-w-5xl px-5 py-12 md:py-16"><Link href={`/jobs/${id}`} className="text-sm font-semibold text-[var(--muted)] hover:text-[var(--orange-dark)]">← Job detail</Link><div className="mt-6 flex flex-col gap-3 border-b border-[var(--border)] pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Live verification</p><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">{verification.title}</h1><p className="mt-2 text-sm text-[var(--muted)]">{verification.agent} · {verification.creator}</p></div>{verification.demo && <span className="status-badge status-neutral">DEMO · SIMULATED</span>}</div>{verification.demo && <div className="mt-8"><AgentSimulator running={running} /></div>}{error && <div role="alert" className="card mt-8 border-[#efb8b0] p-6 text-sm text-[var(--red)]">{error}</div>}{running && !revealed && <div className="mt-8"><StageSequence running={running} result={result} mode={result?.mode ?? "demo"} onDone={() => { setRunning(false); setRevealed(true); }} /></div>}{revealed && result && <div className="stage-in mt-8"><ResultPanel result={result} requirements={verification.requirements} /><div className="mt-8 flex flex-wrap gap-3"><Link href="/demo" className="btn-primary">Run another demo <span aria-hidden>→</span></Link><Link href={`/jobs/${id}`} className="btn-secondary">Back to job</Link></div></div>}</div>;
}
